### ISSUE TITLE
Ability to take URL parameter from the main URL and pass on to IFrame URL

### ISSUE THREAD

**Issue by sebastiangaertner** [einpraegsam/fetchurl#11]
Trying to read the get variables from the requested URL and add them as additional parameters to the iframe URL. Failing with  this Setup. 

```
additionalParameter {
            iframe {
                parameter1 = request.getQueryParams()
                parameter2 = TEXT
                parameter2.value.stdwrap = request.getQueryParams()
                }
        }
```
Any help is appreciated. Thank you.

**Comment by einpraegsam** [comment]
Please use slack or stackoverflow for questions. Github issues is only for bugfixes and features.

Greetings, Alex

**Comment by sebastiangaertner** [comment]
ok. For sure. I did manage in the end. Thanks. Great extension!

**Comment by sebastiangaertner** [comment]
How do i find you on slack?
